apiVersion: apps/v1
kind: Deployment
metadata:
    name: lab2-d
spec:
    selector:
        matchLabels:
            app: lab2
    replicas: 2
    template:
        metadata:
            labels:
                app: lab2
        spec:
            containers:
                - name: lab2-api
                  imagePullPolicy: Never
                  image: ghcr.io/GHCR_USER/sre-lab2:TAG
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: lab2-s
spec:
    type: NodePort
    selector:
        app: lab2
    ports:
        - port: 5000
